### PR TITLE
fix: allow auth token to persist if the browser is closed

### LINKED ISSUE #2544: Users are not captured properly on lbry.tv
I have been going to  beta.lbry.tv and lbry.tv multiple times a week for a number of weeks now. Almost every time I visit, it thinks that I am a new user. 

This has the side effect of misinforming our analytics of the number of users to the site. It is also incorrectly flooding internal-apis with users that are not real users. I flagged it a few weeks back but I see its not fixed yet so I wanted to create an issue so we don't overlook it. 

I would expect we can easily leverage cookies,local storage and ip addresses to get this more accurate.

### PR DESCRIPTION
**Pull request by seanyesmunt**
Fixes #2544 

Not setting an expire time expires the auth token when the session ends.

### CODE REVIEW

File: src/ui/index.jsx [hunk 1]
```diff
@@ -101,6 +104,7 @@ Lbryio.setOverride(
         // @endif
         // @if TARGET='web'
         const { auth_token: authToken } = cookie.parse(document.cookie);
+        console.log('retrieved auth', authToken);
```
Comment (kauffj) [inline src/ui/index.jsx]: Impressive inclusion for such a short PR :grinning: 

Any reason linter did not catch?

Comment (seanyesmunt) [reply src/ui/index.jsx]: 🤦‍♂ 

I turned that lint rule off because it was a pain with all the console logs in our electron files. I'll add it back.
